"""Generator for blackbody_srgb.js (run once; the output is committed).

    pip install colour-science      # (into a scratch --target directory is fine; version used: 0.4.7)
    python3 renders/src/data/make_blackbody_table.py

For each temperature T on a log grid it integrates the Planck spectral radiance B_lambda(T) against the tabulated
CIE 1931 2-degree colour-matching functions (360-830 nm, 1 nm, as shipped by colour-science) to get XYZ, converts
to linear sRGB with the IEC 61966-2-1 matrix, clips negative components, normalizes the brightest component to 1
and applies the sRGB transfer function.  log10 Y (luminance, arbitrary common unit) is stored separately so that
the renderer can compute the visible-band brightness change of a Doppler/gravitationally shifted blackbody
(T_obs = g T is exact for a blackbody; the observed spectrum is a blackbody of temperature g T).
"""
import os
import numpy as np
import colour

H, C, KB = 6.62607015e-34, 299792458.0, 1.380649e-23          # exact SI values (2019 redefinition)
cmfs = colour.MSDS_CMFS['CIE 1931 2 Degree Standard Observer']
lam_nm = cmfs.wavelengths
lam = lam_nm * 1e-9
xbar, ybar, zbar = cmfs.values[:, 0], cmfs.values[:, 1], cmfs.values[:, 2]
M = np.array([[3.2406, -1.5372, -0.4986], [-0.9689, 1.8758, 0.0415], [0.0557, -0.2040, 1.0570]])


def planck(T):
    x = H * C / (lam * KB * T)
    with np.errstate(over='ignore'):
        return (2 * H * C**2 / lam**5) / np.expm1(x)


def srgb_encode(c):
    return np.where(c <= 0.0031308, 12.92 * c, 1.055 * np.power(np.maximum(c, 0), 1 / 2.4) - 0.055)


logT = np.round(np.arange(2.5, 7.0001, 0.025), 4)
rows = []
for lt in logT:
    B = planck(10.0**lt)
    X, Y, Z = (np.trapezoid(B * w, lam_nm) for w in (xbar, ybar, zbar))
    rgb = M @ np.array([X, Y, Z])
    rgb = np.clip(rgb, 0, None)
    rgb = rgb / rgb.max()
    enc = srgb_encode(rgb)
    rows.append((float(lt), float(np.log10(Y)), *[round(float(v), 4) for v in enc]))

here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, 'blackbody_srgb.js'), 'w') as fh:
    fh.write('// GENERATED by renders/src/data/make_blackbody_table.py - do not edit by hand.\n')
    fh.write('// Planck spectrum x CIE 1931 2-deg colour-matching functions (tabulated, via colour-science %s),\n' % colour.__version__)
    fh.write('// XYZ -> linear sRGB (IEC 61966-2-1 matrix), negatives clipped, max component = 1, sRGB-encoded.\n')
    fh.write('// Columns: log10(T/K), log10(Y) (luminance, arbitrary common unit), r, g, b.\n')
    fh.write('export const BB_LOGT0 = %.4f, BB_DLOGT = 0.025;\n' % logT[0])
    fh.write('export const BLACKBODY = [\n')
    for r in rows:
        fh.write('[%.3f,%.5f,%.4f,%.4f,%.4f],\n' % r)
    fh.write('];\n')
print(len(rows), rows[0], rows[len(rows) // 2], rows[-1])
