// Bright-star catalogue for the first-person camera background.
// Data: renders/src/data/stars_mag5.js (generated by data/make_star_catalog.mjs from d3-celestial 0.7.35,
// Copyright (c) 2015 Olaf Frohn, BSD-3-Clause; star source named in the d3-celestial readme: XHIP, Anderson &
// Francis 2012, Astronomy Letters 38, 331, VizieR V/137D).  1627 stars with V <= 5.0, J2000 positions.
import { STARS } from './data/stars_mag5.js';
import { raDecToVec, bvToTemperature } from './firstperson_sky.js';

export const STAR_ATTRIBUTION = 'Stars V ≤ 5 (1627): d3-celestial (© O. Frohn, BSD-3) ← XHIP (Anderson & Francis 2012)';

let cache = null;
export function loadStars() {
  if (cache) return cache;
  cache = STARS.map(([hip, ra, dec, mag, bv]) => ({ hip, ra, dec, mag, bv, vec: raDecToVec(ra, dec), T: bvToTemperature(bv) }));
  return cache;
}
